spring:
  datasource :
    url : jdbc:mariadb://localhost:3306/health
    username : root
    password : 1018

  jpa :
    hibernate :
      ddl-auto : update
      format_sql: true
      show_sql: true

jwt:
  header: Authorization
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64(' '문자열을 base64로 인코딩한 값)
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    me.silvernine: DEBUG

